let config = require("./config").config

var signupTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/><soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_CUST_GET_CUSTOMER_INFO</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?><MSO_OP_CUST_GET_CUSTOMER_INFO_inputFlist><ACCOUNT_NO>{{customerID}}</ACCOUNT_NO><FLAGS>0</FLAGS><PROGRAM_NAME>CALLCENTER</PROGRAM_NAME><POID>0.0.0.0  -1 0</POID><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></MSO_OP_CUST_GET_CUSTOMER_INFO_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;

var customerDetailsTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/><soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_CUST_GET_CUSTOMER_INFO</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?><MSO_OP_CUST_GET_CUSTOMER_INFO_inputFlist><ACCOUNT_NO>{{customerID}}</ACCOUNT_NO><FLAGS>0</FLAGS><PROGRAM_NAME>CALLCENTER</PROGRAM_NAME><POID>0.0.0.0  -1 0</POID><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></MSO_OP_CUST_GET_CUSTOMER_INFO_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;

var getPaymentsTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"> <soapenv:Header/>2 <soapenv:Body> <inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"> <opcode xsi:type="xsd:string">MSO_OP_PYMT_GET_RECEIPTS</opcode> <inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?> <MSO_OP_PYMT_GET_RECEIPTS_inputFlist> <POID>{{poID}}</POID> <MSO_FLD_SERVICE_TYPE>2</MSO_FLD_SERVICE_TYPE> <FLAGS>0</FLAGS> <PROGRAM_NAME>IVR</PROGRAM_NAME> </MSO_OP_PYMT_GET_RECEIPTS_inputFlist> ]]></inputXML> </inf:opcode> </soapenv:Body> </soapenv:Envelope>`;

var renewPricePlanTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/>2<soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_CUST_CALC_PRICE</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?><MSO_OP_CUST_CALC_PRICE_inputFlist><ACTION>ADD PLAN</ACTION><DATA_ARRAY elem="0"><ACCOUNT_OBJ>{{accountObj}}</ACCOUNT_OBJ><PLAN_OBJ>{{planObj}}</PLAN_OBJ><POID>{{accountPoid}}</POID><SERVICE_OBJ>{{serviceObj}}</SERVICE_OBJ><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></DATA_ARRAY><FLAGS>{{flag}}</FLAGS><POID>{{poID}}</POID><PROGRAM_NAME>AFFLE</PROGRAM_NAME></MSO_OP_CUST_CALC_PRICE_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;

var paymentCollectTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/>2<soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_PYMT_COLLECT</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?><MSO_OP_PYMT_COLLECT_inputFlist><PROGRAM_NAME>AFFLE | 3648272752</PROGRAM_NAME><MSO_FLD_PYMT_CHANNEL>10</MSO_FLD_PYMT_CHANNEL><MSO_FLD_SERVICE_TYPE>1</MSO_FLD_SERVICE_TYPE><TYPE>0</TYPE><CHARGES elem="0"><ACCOUNT_OBJ>{{accountObj}}</ACCOUNT_OBJ><AMOUNT>{{amount}}</AMOUNT><COMMAND>0</COMMAND><PAYMENT><INHERITED_INFO><WIRE_TRANSFER_INFO elem="0"><BANK_ACCOUNT_NO></BANK_ACCOUNT_NO><BANK_CODE></BANK_CODE><EFFECTIVE_T>3457345246</EFFECTIVE_T><WIRE_TRANSFER_ID>{{wireTransferId}}</WIRE_TRANSFER_ID></WIRE_TRANSFER_INFO></INHERITED_INFO></PAYMENT><PAY_TYPE>10013</PAY_TYPE></CHARGES><DESCR>Payment through Mobile App | {{remarks}}</DESCR><END_T>{{startDate}}</END_T><POID>{{accountPoid}}</POID><START_T>{{startDate}}</START_T><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></MSO_OP_PYMT_COLLECT_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;

var renewActionTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/>2<soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_CUST_RENEW_BB_PLAN</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8"?><MSO_OP_CUST_RENEW_BB_PLAN_inputFlist><ACCOUNT_OBJ>{{accountObj}}</ACCOUNT_OBJ><PLAN_OBJ>{{planObj}}</PLAN_OBJ><POID>{{accountPoid}}</POID><PROGRAM_NAME>AFFLE</PROGRAM_NAME><SERVICE_OBJ>{{serviceObj}}</SERVICE_OBJ><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></MSO_OP_CUST_RENEW_BB_PLAN_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;

var topupActionTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/>2<soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_CUST_TOP_UP_BB_PLAN</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8"?><MSO_OP_CUST_TOP_UP_BB_PLAN_inputFlist><ACCOUNT_OBJ>{{accountObj}}</ACCOUNT_OBJ><PLAN_OBJ>{{planObj}}</PLAN_OBJ><POID>{{accountPoid}}</POID><PROGRAM_NAME>AFFLE</PROGRAM_NAME><SERVICE_OBJ>{{serviceObj}}</SERVICE_OBJ><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></MSO_OP_CUST_TOP_UP_BB_PLAN_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;

var fupTopupTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/>2<soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_CUST_ADD_PLAN</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8"?><MSO_OP_CUST_ADD_PLAN_inputFlist><ACCOUNT_OBJ>{{accountObj}}</ACCOUNT_OBJ><FLAGS>0</FLAGS><PLAN_LISTS elem="0"><ACTION>ADD</ACTION><PLAN_OBJ>{{planObj}}</PLAN_OBJ><PURCHASE_END_T>1467484200</PURCHASE_END_T></PLAN_LISTS><POID>{{accountPoid}}</POID><PROGRAM_NAME>AFFLE</PROGRAM_NAME><SERVICE_OBJ>{{serviceObj}}</SERVICE_OBJ><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></MSO_OP_CUST_ADD_PLAN_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;

var PushNotification = `<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pus="http://PushNotifyWS/"><soapenv:Header/><soapenv:Body><pus:Signout_App_Notify><account_no>{{customerID}}</account_no><dev_reg_token>{{deviceToken}}</dev_reg_token><dev>{{deviceType}}</dev><status>{{pushStatus}}</status></pus:Signout_App_Notify></soapenv:Body></soapenv:Envelope>`;

var PushUpdateReadStatus = `<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pus="http://PushNotifyWS/"><soapenv:Header/><soapenv:Body><pus:Read_status_update><account_no>{{customerID}}</account_no></pus:Read_status_update></soapenv:Body></soapenv:Envelope>`;

var pushSettingsStatusTemp = `<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pus="http://PushNotifyWS/"><soapenv:Header/><soapenv:Body><pus:Device_status><account_no>{{customerID}}</account_no><dev_reg_token>{{deviceToken}}</dev_reg_token></pus:Device_status></soapenv:Body></soapenv:Envelope>`;

var pushList = `<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pus="http://PushNotifyWS/"><soapenv:Header/><soapenv:Body><pus:User_Notification_Details><account_no>{{customerID}}</account_no></pus:User_Notification_Details></soapenv:Body></soapenv:Envelope>`;

var RegPushNotification = `<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:pus="http://PushNotifyWS/"><soapenv:Header/><soapenv:Body><pus:Newuser_App_Notify><account_no>{{customerID}}</account_no><dev_reg_token>{{deviceToken}}</dev_reg_token><dev>{{deviceType}}</dev></pus:Newuser_App_Notify></soapenv:Body></soapenv:Envelope>`;                    

var changePlanPriceDetail = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/><soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_CUST_CALC_PRICE</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8" standalone="no"?><MSO_OP_CUST_CALC_PRICE_inputFlist><DATA_ARRAY elem="0"><ACCOUNT_OBJ>{{accountObj}}</ACCOUNT_OBJ><BILL_WHEN>{{duration}}</BILL_WHEN><PLAN_LISTS elem="0"><FLAGS>1</FLAGS><PLAN_OBJ>{{newPlanObj}}</PLAN_OBJ></PLAN_LISTS><PLAN_LISTS elem="1"><DEALS elem="0"><DEAL_OBJ>{{dealObj}}</DEAL_OBJ><PACKAGE_ID>{{packageId}}</PACKAGE_ID></DEALS><FLAGS>0</FLAGS><PLAN_OBJ>{{planObj}}</PLAN_OBJ></PLAN_LISTS><POID>{{accountPoid}}</POID><SERVICE_OBJ>{{serviceObj}}</SERVICE_OBJ><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></DATA_ARRAY><FLAGS>5</FLAGS><POID>{{accountPoid}}</POID><PROGRAM_NAME>AFFLE</PROGRAM_NAME></MSO_OP_CUST_CALC_PRICE_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;

var changePlanTemplate = `<soapenv:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:inf="http://202.88.130.103:7104/infranetwebsvc/services/Infranet"><soapenv:Header/><soapenv:Body><inf:opcode soapenv:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><opcode xsi:type="xsd:string">MSO_OP_CUST_CHANGE_PLAN</opcode><inputXML xsi:type="xsd:string"><![CDATA[<?xml version="1.0" encoding="UTF-8"?><MSO_OP_CUST_CHANGE_PLAN_inputFlist><ACCOUNT_OBJ>{{accountObj}}</ACCOUNT_OBJ><BILL_WHEN>{{duration}}</BILL_WHEN><PLAN_LISTS elem="0"><FLAGS>1</FLAGS><PLAN_OBJ>{{newPlanObj}}</PLAN_OBJ></PLAN_LISTS><PLAN_LISTS elem="1"><DEALS elem="0"><DEAL_OBJ>{{dealObj}}</DEAL_OBJ><PACKAGE_ID>{{packageId}}</PACKAGE_ID></DEALS><FLAGS>0</FLAGS><PLAN_OBJ>{{planObj}}</PLAN_OBJ></PLAN_LISTS><POID>{{accountPoid}}</POID><PROGRAM_NAME>AFFLE | Pankaj</PROGRAM_NAME><SERVICE_OBJ>{{serviceObj}}</SERVICE_OBJ><USERID>${config.REF_CONSTANT_USER_ID.userId}</USERID></MSO_OP_CUST_CHANGE_PLAN_inputFlist>]]></inputXML></inf:opcode></soapenv:Body></soapenv:Envelope>`;


var mailTemplate = {
    "from": '"Hathway " <hathwayapptest@gmail.com>',
    "subject": 'Hathway OTP',
    "text": '{{OTP}} is your login OTP. Treat this as confidential. Sharing it with anyone gives them full access to your Hathway account details. Hathway never calls to verify your OTP.'
}

module.exports = {
    signupTemplate: signupTemplate,
    getPaymentsTemplate: getPaymentsTemplate,
    customerDetailsTemplate: customerDetailsTemplate,
    mailTemplate: mailTemplate,
    renewPricePlanTemplate: renewPricePlanTemplate,
    paymentCollectTemplate: paymentCollectTemplate,
    renewActionTemplate: renewActionTemplate,
    topupActionTemplate: topupActionTemplate,
    fupTopupTemplate: fupTopupTemplate,
    PushNotification : PushNotification,
    RegPushNotification : RegPushNotification,
    changePlanTemplate : changePlanTemplate,
    changePlanPriceDetail : changePlanPriceDetail,
    pushList : pushList,
    PushUpdateReadStatus : PushUpdateReadStatus,
    pushSettingsStatusTemp:pushSettingsStatusTemp
};

